@startuml
plantuml
@startgantt
Project starts on 2025-05-01
[Подготовка к внедрению] lasts 1 day
[Подготовка инфраструктуры] lasts 2 days
[Установка ПО] lasts 2 days
[Настройка среды] lasts 1 day
[Обучение] lasts 2 days
[Тестовый запуск] lasts 3 days
[Поддержка] starts at [Тестовый запуск]'s end

[Подготовка к внедрению] -> [Подготовка инфраструктуры]
[Подготовка инфраструктуры] -> [Установка ПО]
[Установка ПО] -> [Настройка среды]
[Настройка среды] -> [Обучение]
[Обучение] -> [Тестовый запуск]
@endgantt
@enduml