@startgantt
Project starts on 2025-05-01
saturday are closed
sunday are closed

[Анализ требований] starts on 2025-05-01 and ends on 2025-05-03
[Проектирование архитектуры] starts on 2025-05-06 and ends on 2025-05-07
[Реализация логики и интерфейса] starts on 2025-05-08 and ends on 2025-05-16

[Модульное тестирование] starts on 2025-05-17 and ends on 2025-05-18
[Интеграционное тестирование] starts on 2025-05-19 and ends on 2025-05-20
[Приёмочное тестирование] starts on 2025-05-21 and ends on 2025-05-21
[Ввод в эксплуатацию] starts on 2025-05-22 and ends on 2025-05-23

[Анализ требований] - [Проектирование архитектуры]
[Проектирование архитектуры] - [Реализация логики и интерфейса]
[Реализация логики и интерфейса] - [Модульное тестирование]
[Модульное тестирование] - [Интеграционное тестирование]
[Интеграционное тестирование] - [Приёмочное тестирование]
[Приёмочное тестирование] - [Ввод в эксплуатацию]

[Веха Анализ завершён] happens on 2025-05-03
[Веха Проектирование завершено] happens on 2025-05-07
[Веха Реализация завершена] happens on 2025-05-16
[Веха Тестирование завершено] happens on 2025-05-21
@endgantt